{{- if .Values.firstApi.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "otel-api-poc.firstApi.serviceAccountName" . }}
  labels:
    {{- include "otel-api-poc.firstApi.labels" . | nindent 4 }}
  {{- with .Values.firstApi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

