{{- if .Values.secondApi.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "otel-api-poc.secondApi.serviceAccountName" . }}
  labels:
    {{- include "otel-api-poc.secondApi.labels" . | nindent 4 }}
  {{- with .Values.secondApi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

